# Generated by Django 4.1 on 2022-10-21 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('brend', models.CharField(max_length=30)),
                ('narx', models.PositiveIntegerField(max_length=30)),
                ('batafsil', models.TextField(max_length=30)),
                ('kafolat', models.CharField(max_length=30)),
                ('yetkazish', models.CharField(max_length=30)),
                ('mavjud', models.CharField(max_length=30)),
                ('chegirma', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='ichki',
            name='bolim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ichkilari', to='asosiyapp.bolim'),
        ),
        migrations.CreateModel(
            name='Rasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm', models.FileField(upload_to='')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.mahsulot')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='ichki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asosiyapp.ichki'),
        ),
    ]
