# Generated by Django 4.1 on 2022-10-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0003_mahsulot_min_order_alter_mahsulot_mavjud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rasm',
            name='mahsulot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rasmlari', to='asosiyapp.mahsulot'),
        ),
    ]
