# Generated by Django 4.1 on 2022-10-25 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiyapp', '0004_alter_rasm_mahsulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='narx',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='rasm',
            name='rasm',
            field=models.FileField(upload_to='mahsulotlar'),
        ),
    ]
